# Lógica da análise
# 1 - Precisamos importar a tabela e mostra-la
# 2 - Fazer uma análise e filtrar o que não é importante 
# 3 - Filtrar melhor o motivo que um cartão leva a ser cancelado naturalmente
# 4 - Analisar anomalias do cancelamento
# 5 - Identificar a causa do cancelamento

In [ ]:
import pandas as pd
tabela_clientes = pd.read_csv("ClientesBilhetagemEletronica -Página1.csv"
                              , encoding="latin1") 
tabela_clientes

,ID CLIENTE,NOME CLIENTE,CARTAO VINCULADO,CHIP CARTAO,STATUS CARTAO,UTILIZACAO,MES UTILIZACAO,IDADE CLIENTE
0,97797,Maria Edileuza,384382612797,777877,Cancelado,BRT,09/2024,65
1,51799,Marcio Silva,643465234898,874571,Cancelado,BRT,10/2024,65
2,74128,Bruno da Costa,113638161974,882975,Ativo,METRO,09/2024,23
3,23935,Bruno da Costa,144761717646,337768,Cancelado,BRT,09/2024,22
4,22891,Bruno Batista,213913611595,763272,Cancelado,METRO,10/2024,65
5,62928,Maria Luiza,587816268424,453495,Ativo,BRT,10/2024,60
6,12857,Maria Eduarda,667586847186,883112,Cancelado,BRT,09/2024,64
7,26979,Maria Clara,741966228342,828855,Ativo,ONIBUS,11/2024,23
8,99451,Ana Clara,679896281864,133882,Ativo,ONIBUS,08/2024,61
9,38479,Lucas Silva,946766389375,546586,Cancelado,BRT,09/2024,63
10,72173,Lucas Moura,359284929785,717966,Cancelado,BRT,09/2024,54
11,34215,Ana Clara,662752835672,534252,Ativo,BRT,10/2024,23
12,84474,Lucas Batista,369528393542,253552,Ativo,BRT,08/2024,20
13,68669,Gabriel Siqueira,734441443324,169889,Ativo,VLT,09/2024,19
14,75489,Julia Silva,884624899921,556894,Ativo,METRO,11/2024,17
15,43237,Carol Mendes,949926878868,161648,Ativo,ONIBUS,11/2024,61
16,51781,Gabriel Silva,634231289638,159663,Cancelado,BRT,10/2024,65
17,52669,Lucas Silva,636712653836,312211,Cancelado,BRT,03/2024,65
18,19262,Lucas Silva,776659618567,392824,Cancelado,BRT,09/2024,23
19,23754,Marcio Silva,848394163288,278112,Cancelado,BRT,09/2024,64

# Excluindo o nome do cliente e número do cartão que não será tão importante, visto que possuímos a ID do cliente e o número do CHIP

In [14]:
tabela_clientes = tabela_clientes.drop ("NOME CLIENTE", axis=1) 
tabela_clientes = tabela_clientes.drop ("CARTAO VINCULADO", axis=1)

# Precisamos mostrar a quantidade e a porcentagem de cartões cancelados e ativos para uma melhor análise

In [15]:
qtd_cartoes = tabela_clientes["STATUS CARTAO"].value_counts()
qtd_cartoes_percentual = tabela_clientes["STATUS CARTAO"].value_counts(normalize=True)
print(qtd_cartoes_percentual)
print(qtd_cartoes)

STATUS CARTAO
Cancelado    0.55
Ativo        0.45
Name: proportion, dtype: float64
STATUS CARTAO
Cancelado    11
Ativo         9
Name: count, dtype: int64

# Agora iremos filtrar cada item importante para que um cartão seja cancelado para depois identificar algum erro.
# Sabemos que no Rio de Janeiro, caso você tenha 65 anos você tem direito a gratuídade, então muitos idosos cancelam seus cartões. 
# Iremos excluir quem possui 65 e visualizar apenas quem possui menos de 65.

In [ ]:
tabela_clientes = pd.read_csv("ClientesBilhetagemEletronica - Página1.csv", encoding="latin1") 
tabela_clientes_filtrado = tabela_clientes[(tabela_clientes["IDADE CLIENTE"] < 65) & (tabela_clientes["STATUS CARTAO"] == "Cancelado")]
tabela_clientes_filtrado

,ID CLIENTE,NOME CLIENTE,CARTAO VINCULADO,CHIP CARTAO,STATUS CARTAO,UTILIZACAO,MES UTILIZACAO,IDADE CLIENTE
3,23935,Bruno da Costa,144761717646,337768,Cancelado,BRT,09/2024,22
6,12857,Maria Eduarda,667586847186,883112,Cancelado,BRT,09/2024,64
9,38479,Lucas Silva,946766389375,546586,Cancelado,BRT,09/2024,63
10,72173,Lucas Moura,359284929785,717966,Cancelado,BRT,09/2024,54
18,19262,Lucas Silva,776659618567,392824,Cancelado,BRT,09/2024,23
19,23754,Marcio Silva,848394163288,278112,Cancelado,BRT,09/2024,64

# Na nossa análise, percebemos que os cartões que foram cancelados tiveram o mesmo padrão de terem sido utilizados no BRT e no mês de 09/2024.
# Agora precisamos saber se o mês de utilização é o fator de terem sido cancelados ou se é o transporte. 
# Para isso iremos filtrar o mês de utilização.

In [18]:
tabela_clientes = pd.read_csv("ClientesBilhetagemEletronica - Página1.csv", encoding="latin1") 
tabela_clientes_filtrado2 = tabela_clientes[(tabela_clientes["IDADE CLIENTE"] < 65) & (tabela_clientes["MES UTILIZACAO"] == "09/2024")]
tabela_clientes_filtrado2

,ID CLIENTE,NOME CLIENTE,CARTAO VINCULADO,CHIP CARTAO,STATUS CARTAO,UTILIZACAO,MES UTILIZACAO,IDADE CLIENTE
2,74128,Bruno da Costa,113638161974,882975,Ativo,METRO,09/2024,23
3,23935,Bruno da Costa,144761717646,337768,Cancelado,BRT,09/2024,22
6,12857,Maria Eduarda,667586847186,883112,Cancelado,BRT,09/2024,64
9,38479,Lucas Silva,946766389375,546586,Cancelado,BRT,09/2024,63
10,72173,Lucas Moura,359284929785,717966,Cancelado,BRT,09/2024,54
13,68669,Gabriel Siqueira,734441443324,169889,Ativo,VLT,09/2024,19
18,19262,Lucas Silva,776659618567,392824,Cancelado,BRT,09/2024,23
19,23754,Marcio Silva,848394163288,278112,Cancelado,BRT,09/2024,64

# Aparentemente não foi apenas o mês de utilização e sim o transporte, mas precisamos saber se em outros meses ele funcionou bem.

In [20]:
tabela_clientes = pd.read_csv("ClientesBilhetagemEletronica - Página1.csv", encoding="latin1") 
tabela_clientes_filtrado3 = tabela_clientes[(tabela_clientes["IDADE CLIENTE"] < 65) & (tabela_clientes["UTILIZACAO"] == "BRT")]
tabela_clientes_filtrado3

,ID CLIENTE,NOME CLIENTE,CARTAO VINCULADO,CHIP CARTAO,STATUS CARTAO,UTILIZACAO,MES UTILIZACAO,IDADE CLIENTE
3,23935,Bruno da Costa,144761717646,337768,Cancelado,BRT,09/2024,22
5,62928,Maria Luiza,587816268424,453495,Ativo,BRT,10/2024,60
6,12857,Maria Eduarda,667586847186,883112,Cancelado,BRT,09/2024,64
9,38479,Lucas Silva,946766389375,546586,Cancelado,BRT,09/2024,63
10,72173,Lucas Moura,359284929785,717966,Cancelado,BRT,09/2024,54
11,34215,Ana Clara,662752835672,534252,Ativo,BRT,10/2024,23
12,84474,Lucas Batista,369528393542,253552,Ativo,BRT,08/2024,20
18,19262,Lucas Silva,776659618567,392824,Cancelado,BRT,09/2024,23
19,23754,Marcio Silva,848394163288,278112,Cancelado,BRT,09/2024,64

# Bom, agora ficou claro o problema. Tivemos algum problema que ocasionou o cancelamento dos cartões no mês de 09/2024 no transporte BRT.